-- INSERT SEMUA LAYANAN LENGKAP KE SUPABASE
INSERT INTO public.services (id, category, name, price, description, badge) VALUES
(1, 'turnitin', 'Cek Turnitin 1x', 'Rp 8.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(2, 'turnitin', 'Cek Turnitin 3x', 'Rp 24.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Hemat!'),
(3, 'turnitin', 'Cek Turnitin 6x', 'Rp 48.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Best Deal!'),
(4, 'turnitin', 'Cek AI 1x', 'Rp 5.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'ZEROGPT'),
(5, 'turnitin', 'Cek AI 2x', 'Rp 10.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'ZEROGPT'),
(6, 'parafrase', 'Parafrase Dokumen', 'Rp 2.000/Hal', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(7, 'joki-tugas', 'Translate Grammar', 'Rp 2.000/Hal', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(8, 'joki-tugas', 'Daftar Pustaka', 'Rp 1.000/Sumber', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(9, 'joki-tugas', 'Pembuatan PPT', 'Rp 3.000/Hal', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(10, 'joki-tugas', 'Daftar Isi Otomatis', 'Rp 10.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(11, 'joki-tugas', 'Pengetikan File', 'Rp 1.000/Hal', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(12, 'joki-tugas', 'Review Jurnal', 'Rp 25.000/Review', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(13, 'joki-tugas', 'Joki Makalah', 'Start Rp 40.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(14, 'joki-tugas', 'Joki Mendeley', 'Rp 1.000/Sumber', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(15, 'joki-tugas', 'Joki Artikel', 'Start Rp 50.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(16, 'joki-tugas', 'Joki Jurnal', 'Start Rp 70.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(17, 'joki-tugas', 'Joki Essay', 'Start Rp 40.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(18, 'joki-tugas', 'Joki Tugas Informatika', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(19, 'joki-tugas', 'Joki Tugas Coding', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(20, 'joki-tugas', 'Joki Pantun Dongeng', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(21, 'joki-tugas', 'Joki Laporan Praktikum', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(22, 'joki-tugas', 'Tugas Fisika/Kimia/Biologi', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(23, 'joki-tugas', 'Tugas MTK/Spatial/Aritmatika', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(24, 'joki-tugas', 'Tugas Hukum/Sosio/Psikologi', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(25, 'joki-tugas', 'Tugas Pendidikan/IPS', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(26, 'joki-tugas', 'Joki Google Colab', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(27, 'joki-tugas', 'Joki Resume / Rangkuman', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(28, 'joki-tugas', 'Tugas SMP,SMA,SMK', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(29, 'joki-tugas', 'Buat Lamaran Kerja', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(30, 'joki-tugas', 'Nomor Halaman', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(31, 'joki-tugas', 'Konsultasi Pemilihan Judul', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(32, 'joki-tugas', 'Bantu Buat Rumusan Masalah', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(33, 'joki-tugas', 'Bantu Buat Tujuan Penelitian', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(34, 'joki-tugas', 'Bantu Buat Manfaat Penelitian', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(35, 'joki-tugas', 'Bantu Susun Kerangka Berpikir', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(36, 'joki-tugas', 'Bantu Susun Kerangka Konsep', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(37, 'joki-tugas', 'Bantu Susun Hipotesis', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(38, 'joki-tugas', 'Bantu Susun Variabel Penelitian', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(39, 'joki-tugas', 'Bantu Identifikasi Gap Penelitian', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(40, 'joki-tugas', 'Bantu Menentukan Metode Penelitian', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(41, 'joki-tugas', 'Bantu Menentukan Populasi & Sampel', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(42, 'joki-tugas', 'Bantu Menentukan Teknik Sampling', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(43, 'joki-tugas', 'Bantu Buat Instrumen Penelitian', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(44, 'joki-tugas', 'Bantu Buat Kisi-Kisi Instrumen', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(45, 'joki-tugas', 'Bantu Buat Kuesioner Penelitian', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(46, 'joki-tugas', 'Bantu Buat Pedoman Wawancara', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(47, 'joki-tugas', 'Bantu Buat Pedoman Observasi', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(48, 'joki-tugas', 'Bantu Buat Alur Penelitian', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(49, 'joki-tugas', 'Bantu Buat Roadmap Penelitian', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(50, 'joki-tugas', 'Bantu Buat Novelty Penelitian', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(51, 'joki-tugas', 'Tugas Akuntansi', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(52, 'joki-tugas', 'Tugas Manajemen', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(53, 'joki-tugas', 'Tugas Pemasaran', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(54, 'joki-tugas', 'Tugas Keuangan', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(55, 'joki-tugas', 'Tugas Perpajakan', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(56, 'joki-tugas', 'Tugas Audit', '100k–350k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(57, 'joki-tugas', 'Tugas Ekonomi Mikro', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(58, 'joki-tugas', 'Tugas Ekonomi Makro', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(59, 'joki-tugas', 'Tugas Administrasi Publik', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(60, 'joki-tugas', 'Tugas Ilmu Komunikasi', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(61, 'joki-tugas', 'Tugas Public Relations', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(62, 'joki-tugas', 'Tugas Broadcasting', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(63, 'joki-tugas', 'Tugas Pariwisata', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(64, 'joki-tugas', 'Tugas Perhotelan', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(65, 'joki-tugas', 'Tugas Teknik Sipil', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(66, 'joki-tugas', 'Tugas Teknik Industri', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(67, 'joki-tugas', 'Tugas Teknik Mesin', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(68, 'joki-tugas', 'Tugas Teknik Elektro', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(69, 'joki-tugas', 'Tugas Arsitektur', '150k–750k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(70, 'joki-tugas', 'Tugas Desain Interior', '150k–750k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(71, 'joki-tugas', 'Tugas DKV', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(72, 'joki-tugas', 'Tugas Keperawatan', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(73, 'joki-tugas', 'Tugas Kebidanan', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(74, 'joki-tugas', 'Tugas Farmasi', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(75, 'joki-tugas', 'Tugas Gizi', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(76, 'joki-tugas', 'Tugas Kesehatan Masyarakat', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(77, 'joki-tugas', 'Tugas Agribisnis', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(78, 'joki-tugas', 'Tugas Peternakan', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(79, 'joki-tugas', 'Tugas Perikanan', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(80, 'joki-tugas', 'Tugas Kehutanan', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(81, 'joki-skripsi', 'Paket Sempro', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(82, 'joki-skripsi', 'Bab 1 / 2 / 3', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Best Seller'),
(83, 'joki-skripsi', 'Cari Referensi', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(84, 'joki-skripsi', 'Paket Lengkap Skripsi', 'Chat Admin', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Termurah'),
(85, 'joki-skripsi', 'Konsultasi Judul Penelitian', '15k–35k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(86, 'joki-skripsi', 'Rekomendasi Judul Penelitian', '25k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(87, 'joki-skripsi', 'Bantu Susun Rumusan Masalah', '20k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(88, 'joki-skripsi', 'Bantu Susun Tujuan Penelitian', '20k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(89, 'joki-skripsi', 'Bantu Susun Manfaat Penelitian', '20k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(90, 'joki-skripsi', 'Bantu Susun Kerangka Berpikir', '40k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(91, 'joki-skripsi', 'Bantu Susun Kerangka Konsep', '40k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(92, 'joki-skripsi', 'Bantu Susun Hipotesis', '25k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(93, 'joki-skripsi', 'Bantu Tentukan Variabel Penelitian', '25k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(94, 'joki-skripsi', 'Bantu Cari Gap Penelitian', '50k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(95, 'joki-skripsi', 'Bantu Tentukan Metode Penelitian', '50k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(96, 'joki-skripsi', 'Bantu Tentukan Populasi & Sampel', '40k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(97, 'joki-skripsi', 'Bantu Teknik Sampling', '35k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(98, 'joki-skripsi', 'Bantu Susun Alur Penelitian', '50k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(99, 'joki-skripsi', 'Bantu Susun Roadmap Penelitian', '75k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(100, 'joki-skripsi', 'Bantu Novelty Penelitian', '75k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(101, 'unlock', 'Unlock Bartleby', 'Rp 2.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(102, 'unlock', 'Unlock Academia', 'Rp 2.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(103, 'unlock', 'Unlock Numerade', 'Rp 3.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(104, 'unlock', 'Unlock Quizlet', 'Rp 2.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(105, 'unlock', 'Unlock Scribd', 'Rp 2.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(106, 'unlock', 'Unlock Chegg', 'Rp 2.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(107, 'unlock', 'Unlock Studocu', 'Rp 3.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(108, 'unlock', 'Unlock Slideshare', 'Rp 3.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(109, 'unlock', 'Unlock Coursehero', 'Rp 3.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(110, 'unlock', 'Unlock Scribd Book', 'Rp 3.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(111, 'unlock', 'Unlock Sage', 'Rp 3.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(112, 'unlock', 'Unlock Wiley', 'Rp 3.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(113, 'unlock', 'Unlock ResearchGate', 'Rp 3.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(114, 'unlock', 'Unlock ISTOR', 'Rp 3.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(115, 'unlock', 'Unlock IEEE', 'Rp 3.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(116, 'unlock', 'Unlock Springer', 'Rp 3.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(117, 'unlock', 'Unlock ACS', 'Rp 4.500', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(118, 'unlock', 'Unlock Elsevier', 'Rp 4.500', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(119, 'unlock', 'Unlock Emerald', 'Rp 4.500', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(120, 'unlock', 'Unlock Oxford', 'Rp 4.500', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(121, 'unlock', 'Unlock Cambridge', 'Rp 4.500', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(122, 'unlock', 'Unlock Nature', 'Rp 4.500', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(123, 'unlock', 'Unlock APA Psycnet', 'Rp 4.500', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(124, 'unlock', 'Unlock Scientific', 'Rp 4.500', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(125, 'joki-skripsi', 'Bantu Buat Kuesioner', '50k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(126, 'joki-skripsi', 'Bantu Buat Kisi-Kisi Instrumen', '40k–120k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(127, 'joki-skripsi', 'Bantu Buat Pedoman Wawancara', '40k–120k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(128, 'uji-data', 'Input Data Kuesioner', 'Rp 25.000–75.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS'),
(129, 'uji-data', 'Cleaning Data (Missing/Outlier)', 'Rp 30.000–80.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS'),
(130, 'uji-data', 'Coding Variabel', 'Rp 30.000–70.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS'),
(131, 'uji-data', 'Uji Validitas', 'Rp 50.000–120.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS'),
(132, 'uji-data', 'Uji Reliabilitas', 'Rp 50.000–120.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS'),
(133, 'uji-data', 'Statistik Deskriptif', 'Rp 30.000–80.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS'),
(134, 'uji-data', 'Uji Normalitas', 'Rp 40.000–100.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS'),
(135, 'uji-data', 'Korelasi Pearson/Spearman', 'Rp 50.000–120.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS'),
(136, 'uji-data', 'Uji T', 'Rp 80.000–150.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS'),
(137, 'uji-data', 'ANOVA', 'Rp 100.000–200.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS'),
(138, 'uji-data', 'Regresi Sederhana', 'Rp 100.000–200.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS'),
(139, 'uji-data', 'Regresi Berganda', 'Rp 150.000–300.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS'),
(140, 'uji-data', 'Uji Multikolinearitas', 'Rp 80.000–150.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS'),
(141, 'uji-data', 'Uji Heteroskedastisitas', 'Rp 80.000–150.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS'),
(142, 'uji-data', 'Interpretasi Bab 4', 'Rp 100.000–300.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS'),
(143, 'uji-data', 'Data Cleaning Python', 'Rp 50.000–150.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python'),
(144, 'uji-data', 'Analisis Statistik Python', 'Rp 80.000–200.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python'),
(145, 'uji-data', 'Visualisasi Data (Matplotlib)', 'Rp 50.000–150.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python'),
(146, 'uji-data', 'Regression Python (Statsmodels)', 'Rp 100.000–250.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python'),
(147, 'uji-data', 'Machine Learning Sederhana', 'Rp 200.000–500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python'),
(148, 'uji-data', 'Clustering Data', 'Rp 150.000–400.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python'),
(149, 'uji-data', 'Google Colab Setup Project', 'Rp 50.000–150.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python'),
(150, 'uji-data', 'Dataset Preprocessing', 'Rp 80.000–200.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python'),
(151, 'uji-data', 'Prediksi Model Sederhana', 'Rp 200.000–500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python'),
(152, 'uji-data', 'Notebook Report (Jupyter/Colab)', 'Rp 100.000–300.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python'),
(153, 'uji-data', 'Model Neural Network Dasar', 'Rp 300.000–800.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'PyTorch'),
(154, 'uji-data', 'Training Model Sederhana', 'Rp 300.000–1.000.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'PyTorch'),
(155, 'uji-data', 'Image Classification Basic', 'Rp 500.000–1.500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'PyTorch'),
(156, 'uji-data', 'NLP Model Sederhana', 'Rp 500.000–1.500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'PyTorch'),
(157, 'uji-data', 'Debugging Model', 'Rp 200.000–600.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'PyTorch'),
(158, 'uji-data', 'Data Cleaning Di R', 'Rp 50.000–150.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'RStudio'),
(159, 'uji-data', 'Descriptive Analysis R', 'Rp 80.000–200.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'RStudio'),
(160, 'uji-data', 'Regresi Linear Di R', 'Rp 100.000–250.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'RStudio'),
(161, 'uji-data', 'ANOVA Di R', 'Rp 100.000–250.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'RStudio'),
(162, 'uji-data', 'Visualisasi Ggplot2', 'Rp 80.000–200.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'RStudio'),
(163, 'uji-data', 'Script R Lengkap Skripsi', 'Rp 200.000–600.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'RStudio'),
(164, 'uji-data', 'Time Series Analysis', 'Rp 150.000–400.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'EViews'),
(165, 'uji-data', 'Uji Stasioneritas', 'Rp 100.000–250.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'EViews'),
(166, 'uji-data', 'Regresi Panel Data', 'Rp 200.000–500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'EViews'),
(167, 'uji-data', 'ARIMA Forecasting', 'Rp 200.000–600.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'EViews'),
(168, 'uji-data', 'Interpretasi Output EViews', 'Rp 100.000–300.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'EViews'),
(169, 'uji-data', 'Setup Database', 'Rp 50.000–150.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database'),
(170, 'uji-data', 'Create Table + Relasi', 'Rp 80.000–200.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database'),
(171, 'uji-data', 'Query SQL Dasar', 'Rp 30.000–100.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database'),
(172, 'uji-data', 'JOIN Query Kompleks', 'Rp 80.000–200.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database'),
(173, 'uji-data', 'Normalisasi Database', 'Rp 150.000–400.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database'),
(174, 'uji-data', 'ERD Database', 'Rp 150.000–400.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database'),
(175, 'uji-data', 'Export/Import Data', 'Rp 30.000–100.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database'),
(176, 'uji-data', 'Debug SQL Error', 'Rp 50.000–150.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database'),
(177, 'uji-data', 'Olah Data Excel + Pivot + Chart', 'Rp 30.000–150.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Excel'),
(178, 'uji-data', 'Uji Chi-Square', 'Rp 70.000–150.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS Lanjutan'),
(179, 'uji-data', 'Uji Fisher Exact', 'Rp 70.000–150.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS Lanjutan'),
(180, 'uji-data', 'Uji Mann-Whitney', 'Rp 80.000–160.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS Lanjutan'),
(181, 'uji-data', 'Uji Wilcoxon', 'Rp 80.000–160.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS Lanjutan'),
(182, 'uji-data', 'Uji Kruskal-Wallis', 'Rp 100.000–200.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS Lanjutan'),
(183, 'uji-data', 'Uji Friedman', 'Rp 100.000–200.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS Lanjutan'),
(184, 'uji-data', 'Uji Path Analysis Sederhana', 'Rp 150.000–350.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS Lanjutan'),
(185, 'uji-data', 'Uji Sobel (Mediasi)', 'Rp 150.000–300.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS Lanjutan'),
(186, 'uji-data', 'Moderasi (Interaction Effect)', 'Rp 150.000–300.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS Lanjutan'),
(187, 'uji-data', 'Uji Linearitas SPSS', 'Rp 50.000–120.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'SPSS Lanjutan'),
(188, 'uji-data', 'Feature Engineering Dataset', 'Rp 100.000–300.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python Lanjut'),
(189, 'uji-data', 'Handling Missing Value Advanced', 'Rp 80.000–200.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python Lanjut'),
(190, 'uji-data', 'Encoding Data Kategorikal', 'Rp 80.000–200.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python Lanjut'),
(191, 'uji-data', 'Scaling/Normalization Data', 'Rp 80.000–200.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python Lanjut'),
(192, 'uji-data', 'Outlier Detection Python', 'Rp 100.000–250.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python Lanjut'),
(193, 'uji-data', 'Data Pipeline Sederhana', 'Rp 200.000–500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python Lanjut'),
(194, 'uji-data', 'Cross-Validation Model', 'Rp 200.000–500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python Lanjut'),
(195, 'uji-data', 'Model Evaluation (Accuracy, Precision)', 'Rp 150.000–400.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python Lanjut'),
(196, 'uji-data', 'Confusion Matrix Analysis', 'Rp 100.000–250.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python Lanjut'),
(197, 'uji-data', 'Time Series Forecasting Python', 'Rp 250.000–600.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Python Lanjut'),
(198, 'uji-data', 'Logistic Regression Model', 'Rp 200.000–500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Machine Learning'),
(199, 'uji-data', 'Decision Tree Model', 'Rp 200.000–500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Machine Learning'),
(200, 'uji-data', 'Random Forest Basic', 'Rp 300.000–700.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Machine Learning'),
(201, 'uji-data', 'SVM Classification', 'Rp 300.000–700.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Machine Learning'),
(202, 'uji-data', 'Neural Network Tuning', 'Rp 400.000–1.000.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Machine Learning'),
(203, 'uji-data', 'Hyperparameter Tuning', 'Rp 300.000–800.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Machine Learning'),
(204, 'uji-data', 'Model Comparison Analysis', 'Rp 200.000–500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Machine Learning'),
(205, 'uji-data', 'Dataset Labeling Support', 'Rp 150.000–400.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Machine Learning'),
(206, 'uji-data', 'AI Model Optimization', 'Rp 500.000–1.500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Machine Learning'),
(207, 'uji-data', 'Training Deep Learning Model', 'Rp 500.000–2.000.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Machine Learning'),
(208, 'uji-data', 'Data Wrangling Di R (Dplyr)', 'Rp 80.000–200.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'RStudio Lanjut'),
(209, 'uji-data', 'Time Series R (Forecast Package)', 'Rp 200.000–500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'RStudio Lanjut'),
(210, 'uji-data', 'Regression Diagnostics R', 'Rp 150.000–300.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'RStudio Lanjut'),
(211, 'uji-data', 'Logistic Regression R', 'Rp 150.000–300.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'RStudio Lanjut'),
(212, 'uji-data', 'Survival Analysis R', 'Rp 300.000–700.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'RStudio Lanjut'),
(213, 'uji-data', 'Multivariate Analysis R', 'Rp 300.000–700.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'RStudio Lanjut'),
(214, 'uji-data', 'Correlation Matrix Heatmap', 'Rp 100.000–250.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'RStudio Lanjut'),
(215, 'uji-data', 'Data Reshaping R', 'Rp 80.000–200.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'RStudio Lanjut'),
(216, 'uji-data', 'Advanced Ggplot Dashboard', 'Rp 150.000–400.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'RStudio Lanjut'),
(217, 'uji-data', 'R Markdown Report', 'Rp 150.000–300.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'RStudio Lanjut'),
(218, 'uji-data', 'Vector Autoregression (VAR)', 'Rp 300.000–700.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'EViews Lanjut'),
(219, 'uji-data', 'Cointegration Test', 'Rp 250.000–600.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'EViews Lanjut'),
(220, 'uji-data', 'Error Correction Model (ECM)', 'Rp 250.000–600.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'EViews Lanjut'),
(221, 'uji-data', 'Panel Data Fixed Effect', 'Rp 200.000–500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'EViews Lanjut'),
(222, 'uji-data', 'Random Effect Model', 'Rp 200.000–500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'EViews Lanjut'),
(223, 'uji-data', 'Granger Causality Test', 'Rp 200.000–500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'EViews Lanjut'),
(224, 'uji-data', 'Impulse Response Analysis', 'Rp 300.000–700.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'EViews Lanjut'),
(225, 'uji-data', 'Forecast Evaluation EViews', 'Rp 200.000–500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'EViews Lanjut'),
(226, 'uji-data', 'Model Selection Econometrics', 'Rp 150.000–400.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'EViews Lanjut'),
(227, 'uji-data', 'Stored Procedure & Function SQL', 'Rp 150.000–400.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database Lanjut'),
(228, 'uji-data', 'Trigger Database Automation', 'Rp 200.000–500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database Lanjut'),
(229, 'uji-data', 'View Optimization SQL', 'Rp 100.000–300.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database Lanjut'),
(230, 'uji-data', 'Query Optimization Tuning', 'Rp 150.000–400.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database Lanjut'),
(231, 'uji-data', 'Database Indexing Setup', 'Rp 150.000–350.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database Lanjut'),
(232, 'uji-data', 'Backup Automation SQL', 'Rp 100.000–250.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database Lanjut'),
(233, 'uji-data', 'API Database Integration', 'Rp 300.000–800.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database Lanjut'),
(234, 'uji-data', 'Data Migration Database', 'Rp 200.000–600.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database Lanjut'),
(235, 'uji-data', 'Relational Schema Redesign', 'Rp 200.000–500.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database Lanjut'),
(236, 'uji-data', 'Big Dataset SQL Processing', 'Rp 300.000–700.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Database Lanjut'),
(237, 'uji-data', 'Pivot Table Advanced Analysis', 'Rp 50.000–150.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Excel Lanjut'),
(238, 'uji-data', 'Dashboard Excel Interaktif', 'Rp 150.000–400.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Excel Lanjut'),
(239, 'uji-data', 'Power Query Cleaning', 'Rp 100.000–300.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Excel Lanjut'),
(240, 'uji-data', 'Macro/VBA Automation', 'Rp 200.000–600.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Excel Lanjut'),
(241, 'uji-data', 'Forecasting Excel Model', 'Rp 100.000–300.000', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', 'Excel Lanjut'),
(242, 'tugas-sekolah', 'Latihan Soal Harian', '10k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(243, 'tugas-sekolah', 'Pembahasan Soal', '15k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(244, 'tugas-sekolah', 'Bank Soal Mandiri', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(245, 'tugas-sekolah', 'Mind Map Materi', '15k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(246, 'tugas-sekolah', 'Catatan Estetik', '15k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(247, 'tugas-sekolah', 'Kartu Hafalan', '15k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(248, 'tugas-sekolah', 'Ringkasan Per Bab Versi Poin', '15k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(249, 'tugas-sekolah', 'Tugas Kliping', '20k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(250, 'tugas-sekolah', 'Tugas Poster Edukasi', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(251, 'tugas-sekolah', 'Tugas Infografis Sekolah', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(252, 'tugas-sekolah', 'Tugas Mading', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(253, 'tugas-sekolah', 'Tugas Biografi Tokoh', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(254, 'tugas-sekolah', 'Tugas Autobiografi', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(255, 'tugas-sekolah', 'Tugas Teks Pidato', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(256, 'tugas-sekolah', 'Tugas Teks MC', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(257, 'tugas-sekolah', 'Tugas Teks Drama', '40k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(258, 'tugas-sekolah', 'Tugas Teks Negosiasi', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(259, 'tugas-sekolah', 'Tugas Teks Eksposisi', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(260, 'tugas-sekolah', 'Tugas Teks Eksplanasi', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(261, 'tugas-sekolah', 'Tugas Teks Prosedur', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(262, 'tugas-sekolah', 'Tugas Teks Anekdot', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(263, 'tugas-sekolah', 'Tugas Teks Deskripsi', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(264, 'tugas-sekolah', 'Tugas Teks Argumentasi', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(265, 'tugas-sekolah', 'Tugas Surat Pribadi', '15k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(266, 'tugas-sekolah', 'Tugas Surat Dinas', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(267, 'tugas-sekolah', 'Tugas Cerita Inspiratif', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(268, 'tugas-sekolah', 'Tugas Resensi Buku', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(269, 'tugas-sekolah', 'Tugas Sinopsis Film', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(270, 'tugas-sekolah', 'Tugas Analisis Cerpen', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(271, 'tugas-sekolah', 'Tugas Analisis Novel', '40k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(272, 'tugas-sekolah', 'Laporan Study Tour', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(273, 'tugas-sekolah', 'Laporan Kunjungan Museum', '40k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(274, 'tugas-sekolah', 'Laporan Observasi Lingkungan', '40k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(275, 'tugas-sekolah', 'Laporan Wawancara Tokoh', '40k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(276, 'tugas-sekolah', 'Laporan Kegiatan Sekolah', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(277, 'tugas-sekolah', 'Proposal Kegiatan Kelas', '40k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(278, 'tugas-sekolah', 'Proposal Kegiatan OSIS', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(279, 'tugas-sekolah', 'Proposal Kegiatan Pramuka', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(280, 'tugas-sekolah', 'Proposal Kegiatan Ekskul', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(281, 'tugas-sekolah', 'Program Kerja OSIS', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(282, 'tugas-sekolah', 'Program Kerja Ekskul', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(283, 'tugas-sekolah', 'Struktur Kepanitiaan', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(284, 'tugas-sekolah', 'Rundown Acara Sekolah', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(285, 'tugas-sekolah', 'Teks Sambutan Acara', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(286, 'tugas-sekolah', 'Teks Moderator', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(287, 'tugas-sekolah', 'Teks Debat', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(288, 'tugas-sekolah', 'Naskah Drama Sekolah', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(289, 'tugas-sekolah', 'Naskah Video Edukasi', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(290, 'tugas-sekolah', 'Script Presentasi Video', '40k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(291, 'tugas-sekolah', 'Konsep Project P5', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(292, 'tugas-sekolah', 'Laporan Project P5', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(293, 'tugas-sekolah', 'Jurnal Kegiatan P5', '40k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(294, 'tugas-sekolah', 'Ide Produk Kewirausahaan Sekolah', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(295, 'tugas-sekolah', 'Laporan Kewirausahaan Sekolah', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(296, 'tugas-sekolah', 'Tugas Bahasa Indonesia', '15k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(297, 'tugas-sekolah', 'Tugas Bahasa Inggris', '20k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(298, 'tugas-sekolah', 'Tugas Bahasa Daerah', '20k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(299, 'tugas-sekolah', 'Tugas Bahasa Jepang', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(300, 'tugas-sekolah', 'Tugas Bahasa Mandarin', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(301, 'tugas-sekolah', 'Tugas Bahasa Arab', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(302, 'tugas-sekolah', 'Tugas Sejarah', '20k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(303, 'tugas-sekolah', 'Tugas Geografi', '20k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(304, 'tugas-sekolah', 'Tugas Ekonomi', '25k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(305, 'tugas-sekolah', 'Tugas Akuntansi Dasar', '30k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(306, 'tugas-sekolah', 'Tugas PKN', '20k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(307, 'tugas-sekolah', 'Tugas Agama', '20k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(308, 'tugas-sekolah', 'Tugas Seni Budaya', '25k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(309, 'tugas-sekolah', 'Tugas Prakarya', '25k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(310, 'tugas-sekolah', 'Tugas PJOK', '20k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(311, 'tugas-sekolah', 'Tugas Kewirausahaan', '30k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(312, 'tugas-sekolah', 'Tugas Administrasi Perkantoran', '30k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(313, 'tugas-sekolah', 'Tugas Multimedia', '50k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(314, 'tugas-sekolah', 'Tugas Desain Grafis', '50k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(315, 'tugas-sekolah', 'Tugas TKJ', '50k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(316, 'tugas-sekolah', 'Tugas RPL Non-Coding', '40k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(317, 'tugas-sekolah', 'Tugas Perhotelan SMK', '30k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(318, 'tugas-sekolah', 'Tugas Tata Boga', '30k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(319, 'tugas-sekolah', 'Tugas Tata Busana', '30k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(320, 'tugas-sekolah', 'Tugas Otomotif', '50k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(321, 'tugas-sekolah', 'Tugas Akuntansi SMK', '30k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(322, 'tugas-sekolah', 'Tugas Pemasaran SMK', '30k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(323, 'umum', 'Entry Data', '25k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(324, 'umum', 'Rekap Data Excel', '25k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(325, 'umum', 'Input Database', '50k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(326, 'umum', 'Rapikan Database', '50k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(327, 'umum', 'Template Absensi', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(328, 'umum', 'Template Invoice', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(329, 'umum', 'Template Kwitansi', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(330, 'umum', 'Template Surat Jalan', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(331, 'umum', 'Template Laporan Harian', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(332, 'umum', 'Template Laporan Mingguan', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(333, 'umum', 'Template Laporan Bulanan', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(334, 'umum', 'Formulir Digital', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(335, 'umum', 'Google Form', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(336, 'umum', 'Survey Online', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(337, 'umum', 'Notulen Meeting', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(338, 'umum', 'Minutes of Meeting', '75k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(339, 'umum', 'Agenda Meeting', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(340, 'umum', 'Rundown Acara Kantor', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(341, 'umum', 'SOP Kerja', '150k–750k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(342, 'umum', 'Job Description', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(343, 'umum', 'KPI Karyawan', '150k–750k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(344, 'umum', 'Struktur Organisasi', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(345, 'umum', 'Timeline Project', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(346, 'umum', 'Checklist Kerja', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(347, 'umum', 'Template Monitoring Project', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(348, 'umum', 'Proposal Bisnis', '150k–750k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(349, 'umum', 'Company Profile', '200k–1.000k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(350, 'umum', 'Pitch Deck Bisnis', '250k–1.500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(351, 'umum', 'Analisis SWOT', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(352, 'umum', 'Analisis Kompetitor', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(353, 'umum', 'Analisis Target Pasar', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(354, 'umum', 'Riset Pasar', '150k–1.000k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(355, 'umum', 'Riset Produk', '75k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(356, 'umum', 'Riset Harga Kompetitor', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(357, 'umum', 'Business Model Canvas', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(358, 'umum', 'Perhitungan HPP', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(359, 'umum', 'Perhitungan BEP', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(360, 'umum', 'Perhitungan Margin Profit', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(361, 'umum', 'Laporan Penjualan', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(362, 'umum', 'Laporan Stok Barang', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(363, 'umum', 'Laporan Keuangan Sederhana', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(364, 'umum', 'Pembukuan UMKM', '150k–750k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(365, 'umum', 'Catatan Kas Masuk Keluar', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(366, 'umum', 'Template Inventory', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(367, 'umum', 'Template Orderan', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(368, 'umum', 'Template Customer Database', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(369, 'umum', 'Deskripsi Produk Marketplace', '5k–25k/produk', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(370, 'umum', 'Optimasi Judul Produk', '5k–20k/produk', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(371, 'umum', 'Ide Nama Brand', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(372, 'umum', 'Slogan Brand', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(373, 'umum', 'Konsep Branding UMKM', '150k–750k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(374, 'umum', 'Optimasi Profil LinkedIn', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(375, 'umum', 'Bio Profesional', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(376, 'umum', 'Portofolio Kerja', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(377, 'umum', 'Personal Branding', '150k–750k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(378, 'umum', 'Surat Resign', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(379, 'umum', 'Surat Rekomendasi', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(380, 'umum', 'Surat Pernyataan', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(381, 'umum', 'Surat Kuasa', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(382, 'umum', 'Surat Kerja Sama', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(383, 'umum', 'Surat Penawaran', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(384, 'umum', 'Surat Permohonan', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(385, 'umum', 'Surat Undangan Resmi', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(386, 'umum', 'Surat Komplain', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(387, 'umum', 'Surat Balasan Kerja Sama', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(388, 'umum', 'Email Profesional', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(389, 'umum', 'Email Follow Up', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(390, 'umum', 'Email Penawaran Bisnis', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(391, 'umum', 'Email Customer Service', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(392, 'umum', 'Script Interview Kerja', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(393, 'umum', 'Simulasi Jawaban Interview', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(394, 'umum', 'Profil Singkat Freelancer', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(395, 'umum', 'Bio Marketplace Freelancer', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(396, 'medsos', 'Caption Instagram', '5k–25k/caption', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(397, 'medsos', 'Caption TikTok', '5k–25k/caption', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(398, 'medsos', 'Copywriting Produk', '15k–75k/produk', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(399, 'medsos', 'Copywriting Iklan', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(400, 'medsos', 'Caption Marketplace', '5k–25k/produk', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(401, 'medsos', 'Script TikTok', '25k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(402, 'medsos', 'Script Reels', '25k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(403, 'medsos', 'Script YouTube Shorts', '25k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(404, 'medsos', 'Script Voice Over', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(405, 'medsos', 'Ide Konten Harian', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(406, 'medsos', 'Kalender Konten', '150k–750k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(407, 'medsos', 'Content Plan Mingguan', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(408, 'medsos', 'Content Plan Bulanan', '250k–1.500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(409, 'medsos', 'Artikel Blog', '50k–250k/artikel', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(410, 'medsos', 'Artikel SEO', '75k–400k/artikel', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(411, 'medsos', 'Deskripsi Video YouTube', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(412, 'medsos', 'Judul Konten Viral', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(413, 'medsos', 'Riset Hashtag', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(414, 'medsos', 'Bio Instagram Bisnis', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(415, 'medsos', 'Balasan Chat Customer', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(416, 'medsos', 'Template Chat Admin', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(417, 'medsos', 'Template Broadcast WhatsApp', '25k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(418, 'medsos', 'Template Promo Produk', '25k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(419, 'medsos', 'Template Testimoni', '15k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(420, 'desain', 'Desain Logo', '75k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(421, 'desain', 'Desain Banner', '50k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(422, 'desain', 'Desain Brosur', '50k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(423, 'desain', 'Desain Flyer', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(424, 'desain', 'Desain Menu Makanan', '50k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(425, 'desain', 'Desain Poster Sekolah', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(426, 'desain', 'Desain Jadwal Piket', '15k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(427, 'desain', 'Desain Struktur Kelas', '15k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(428, 'desain', 'Desain Sertifikat Kelas', '15k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(429, 'desain', 'Desain ID Card Panchunta', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(430, 'desain', 'Desain Brosur Sekolah', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(431, 'desain', 'Desain Pamflet Acara', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(432, 'desain', 'Desain Twibbon', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(433, 'desain', 'Desain Feed OSIS', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(434, 'desain', 'Desain Story Instagram Sekolah', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(435, 'desain', 'Desain Cover Tugas', '10k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(436, 'desain', 'Desain Sampul Kliping', '10k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(437, 'desain', 'Desain Modul Belajar', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(438, 'desain', 'Desain Lembar Kerja Siswa', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(439, 'desain', 'Desain Kartu Ucapan Guru', '15k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(440, 'desain', 'Desain Undangan Acara Sekolah', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(441, 'desain', 'Desain Cover Makalah', 'Start 15k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(442, 'desain', 'Desain Cover Laporan', 'Start 15k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(443, 'desain', 'Desain Katalog Produk', '150k–750k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(444, 'desain', 'Desain Price List', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(445, 'desain', 'Desain Sertifikat', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(446, 'desain', 'Desain Undangan Digital', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(447, 'desain', 'Desain Kartu Nama', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(448, 'desain', 'Desain Stiker Produk', '25k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(449, 'desain', 'Desain Label Kemasan', '50k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(450, 'desain', 'Desain Packaging', '150k–1.000k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(451, 'desain', 'Desain Feed Instagram', '25k–150k/post', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(452, 'desain', 'Desain Story Instagram', '20k–100k/story', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(453, 'desain', 'Desain Thumbnail YouTube', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(454, 'desain', 'Desain Cover Ebook', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(455, 'desain', 'Desain Poster Event', '50k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(456, 'desain', 'Desain Spanduk', '75k–400k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(457, 'desain', 'Desain X-Banner', '75k–400k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(458, 'desain', 'Edit PDF Ringan', '10k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(459, 'desain', 'Gabung File PDF', '5k–25k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(460, 'desain', 'Pisah File PDF', '5k–25k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(461, 'desain', 'Kompres PDF', '5k–20k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(462, 'desain', 'Watermark Dokumen', '10k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(463, 'desain', 'Hapus Watermark Milik Sendiri', '10k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(464, 'desain', 'Convert Gambar ke PDF', '5k–25k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(465, 'desain', 'Convert Word ke PDF', '5k–20k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(466, 'desain', 'Convert Excel ke PDF', '5k–20k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(467, 'desain', 'Rapikan Layout Dokumen', '10k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(468, 'desain', 'Buat Template Dokumen', '25k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(469, 'desain', 'Buat Kop Surat', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(470, 'desain', 'Buat Form Isian', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(471, 'desain', 'Buat E-Certificate', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(472, 'desain', 'Buat Barcode / QR Code', '10k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(473, 'desain', 'Buat Label Nama', '10k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(474, 'desain', 'Buat Nomor Antrian', '10k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(475, 'desain', 'Buat Kartu Panchunta', '20k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(476, 'desain', 'Buat Kartu Member', '20k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(477, 'desain', 'Proposal Event', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(478, 'desain', 'Rundown Event', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(479, 'desain', 'Susunan Acara', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(480, 'desain', 'Teks MC Formal', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(481, 'desain', 'Teks MC Nonformal', '40k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(482, 'desain', 'Teks Sambutan Ketua Panchunta', '40k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(483, 'desain', 'Teks Sambutan Pembina', '40k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(484, 'desain', 'Teks Moderator Seminar', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(485, 'desain', 'Term of Reference Acara', '100k–400k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(486, 'desain', 'Timeline Kepanitiaan', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(487, 'desain', 'Jobdesk Panchunta', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(488, 'desain', 'Form Registrasi Acara', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(489, 'desain', 'Sertifikat Peserta', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(490, 'desain', 'Sertifikat Panchunta', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(491, 'desain', 'Desain Background Zoom', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(492, 'desain', 'Desain Name Tag', '20k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(493, 'desain', 'Rekap Kehadiran Peserta', '25k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(494, 'desain', 'LPJ Acara', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(495, 'desain', 'Desain Cover Proposal', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(496, 'desain', 'Desain Cover Skripsi / Tugas Akhir', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(497, 'desain', 'Desain Layout Makalah', '25k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(498, 'desain', 'Desain Layout Proposal', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(499, 'desain', 'Desain Layout Laporan Praktik', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(500, 'desain', 'Desain E-Modul Sekolah', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(501, 'desain', 'Desain Infografis Materi', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(502, 'desain', 'Desain Mind Map Digital', '20k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(503, 'desain', 'Desain Timeline Sejarah', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(504, 'desain', 'Desain Jadwal Pelajaran', '10k–50k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(505, 'desain', 'Desain Kartu Hafalan', '15k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(506, 'desain', 'Desain Flashcard Edukasi', '25k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(507, 'desain', 'Desain Lembar Catatan Estetik', '15k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(508, 'desain', 'Desain Template Catatan Sekolah', '20k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(509, 'desain', 'Desain Carousel Instagram', '50k–250k/paket', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(510, 'desain', 'Desain Highlight Instagram', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(511, 'desain', 'Desain Cover Highlight', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(512, 'desain', 'Desain Template Reels Cover', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(513, 'desain', 'Desain Template TikTok Cover', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(514, 'desain', 'Desain Header Facebook', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(515, 'desain', 'Desain Sampul Grup Facebook', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(516, 'desain', 'Desain Header Twitter / X', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(517, 'desain', 'Desain Header LinkedIn', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(518, 'desain', 'Desain Profil Marketplace', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(519, 'desain', 'Desain Bio Link Page', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(520, 'desain', 'Desain Template Promo Harian', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(521, 'desain', 'Desain Template Testimoni', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(522, 'desain', 'Desain Template Giveaway', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(523, 'desain', 'Desain Template Open Order', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(524, 'desain', 'Desain Template Close Order', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(525, 'desain', 'Desain Template Flash Sale', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(526, 'desain', 'Desain Template Pengumuman', '20k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(527, 'desain', 'Desain Template Quotes', '15k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(528, 'desain', 'Desain Template Edukasi Konten', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(529, 'desain', 'Desain Brand Guideline Sederhana', '150k–750k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(530, 'desain', 'Desain Brand Board', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(531, 'desain', 'Desain Moodboard Brand', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(532, 'desain', 'Desain Palet Warna Brand', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(533, 'desain', 'Desain Tipografi Brand', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(534, 'desain', 'Desain Stationery Kit', '150k–750k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(535, 'desain', 'Desain Kop Surat', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(536, 'desain', 'Desain Invoice Brand', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(537, 'desain', 'Desain Kwitansi Brand', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(538, 'desain', 'Desain Form Order', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(539, 'desain', 'Desain Template Surat Bisnis', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(540, 'desain', 'Desain Proposal Bisnis Visual', '150k–750k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(541, 'desain', 'Desain Company Profile Visual', '200k–1.000k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(542, 'desain', 'Desain Pitch Deck Startup', '250k–1.500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(543, 'desain', 'Desain Media Kit', '150k–750k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(544, 'desain', 'Desain Rate Card Influencer', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(545, 'desain', 'Desain Rate Card Jasa', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(546, 'desain', 'Desain Portofolio Bisnis', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(547, 'desain', 'Desain Profil UMKM', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(548, 'desain', 'Desain Template Branding Produk', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(549, 'desain', 'Desain Cover Toko Shopee', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(550, 'desain', 'Desain Cover Toko Tokopedia', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(551, 'desain', 'Desain Cover Toko TikTok Shop', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(552, 'desain', 'Desain Dekorasi Toko Marketplace', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(553, 'desain', 'Desain Etalase Produk', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(554, 'desain', 'Desain Foto Produk Marketplace', '25k–150k/foto', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(555, 'desain', 'Desain Frame Foto Produk', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(556, 'desain', 'Desain Template Promo Marketplace', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(557, 'desain', 'Desain Voucher Marketplace', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(558, 'desain', 'Desain Flash Sale Marketplace', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(559, 'desain', 'Desain Produk Best Seller Badge', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(560, 'desain', 'Desain Produk New Arrival Badge', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(561, 'desain', 'Desain Template Review Produk', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(562, 'desain', 'Desain Panduan Ukuran Produk', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(563, 'desain', 'Desain Cara Order Produk', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(564, 'desain', 'Desain Alur Pemesanan', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(565, 'desain', 'Desain Kartu Terima Kasih', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(566, 'desain', 'Desain Kartu Garansi Produk', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(567, 'desain', 'Desain Kartu Perawatan Produk', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(568, 'desain', 'Desain Insert Card Paket', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(569, 'desain', 'Desain Virtual Background Seminar', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(570, 'desain', 'Desain ID Card Event', '25k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(571, 'desain', 'Desain Kartu Peserta', '20k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(572, 'desain', 'Desain Tiket Acara', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(573, 'desain', 'Desain Kupon Acara', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(574, 'desain', 'Desain Wristband Event', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(575, 'desain', 'Desain Layout Booth', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(576, 'desain', 'Desain Denah Acara', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(577, 'desain', 'Desain Signage Acara', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(578, 'desain', 'Desain Papan Informasi', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(579, 'desain', 'Desain Doorprize Card', '20k–75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(580, 'desain', 'Desain Template Rundown Panchunta', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(581, 'desain', 'Desain Template Absensi Acara', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(582, 'desain', 'Desain Template Evaluasi Acara', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(583, 'desain', 'Desain E-Ticket', '30k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(584, 'desain', 'Desain QR Check-In Event', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(585, 'desain', 'Desain Thank You Card Event', '25k–100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(586, 'desain', 'Desain CV Kreatif', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(587, 'desain', 'Desain CV ATS Visual', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(588, 'desain', 'Desain Resume Profesional', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(589, 'desain', 'Desain Portofolio Freelancer', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(590, 'desain', 'Desain Personal Profile', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(591, 'desain', 'Desain Personal Branding Kit', '150k–750k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(592, 'desain', 'Desain Cover Letter Visual', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(593, 'desain', 'Desain Profil LinkedIn Banner', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(594, 'desain', 'Desain Media Kit Personal', '150k–750k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(595, 'desain', 'Desain Rate Card Freelancer', '50k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(596, 'desain', 'Desain Proposal Kerja Sama Personal', '100k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(597, 'desain', 'Desain One Page Profile', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(598, 'desain', 'Desain Biodata Profesional', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(599, 'desain', 'Desain Portofolio Magang', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(600, 'digital', 'Upload Produk Marketplace', '3k–15k/produk', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(601, 'laporan-akademik', 'Proposal Penelitian', '150k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(602, 'laporan-akademik', 'Proposal Kegiatan Kampus', '75k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(603, 'laporan-akademik', 'Proposal PKM', '150k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(604, 'laporan-akademik', 'Proposal Magang', '75k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(605, 'laporan-akademik', 'Proposal KKN', '75k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(606, 'laporan-akademik', 'Proposal Bisnis Mahasiswa', '150k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(607, 'laporan-akademik', 'Laporan Magang', '150k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(608, 'laporan-akademik', 'Laporan KKN', '150k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(609, 'laporan-akademik', 'Laporan PKL Kuliah', '150k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(610, 'laporan-akademik', 'Laporan Observasi', '75k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(611, 'laporan-akademik', 'Laporan Studi Kasus', '100k–350k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(612, 'laporan-akademik', 'Laporan Field Trip', '75k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(613, 'laporan-akademik', 'Laporan Kunjungan Industri', '75k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(614, 'laporan-akademik', 'Laporan Mini Riset', '100k–350k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(615, 'laporan-akademik', 'Laporan Hasil Wawancara', '75k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(616, 'laporan-akademik', 'Laporan Pengabdian Masyarakat', '150k–500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(617, 'laporan-akademik', 'Laporan Kegiatan Organisasi', '75k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(618, 'laporan-akademik', 'Logbook Magang', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(619, 'laporan-akademik', 'Logbook KKN', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(620, 'laporan-akademik', 'Portofolio Kuliah', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(621, 'laporan-akademik', 'Tugas Case Study', '75k–300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(622, 'laporan-akademik', 'Tugas Critical Thinking', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(623, 'laporan-akademik', 'Tugas Analisis Film', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(624, 'laporan-akademik', 'Tugas Analisis Buku', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(625, 'laporan-akademik', 'Tugas Analisis Berita', '50k–200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(626, 'laporan-akademik', 'Tugas Analisis Kebijakan', '100k–350k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(627, 'laporan-akademik', 'Tugas Studi Literatur', '100k–350k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(628, 'laporan-akademik', 'Tugas Annotated Bibliography', '75k–250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(629, 'laporan-akademik', 'Tugas Opini Akademik', '40k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(630, 'laporan-akademik', 'Tugas Refleksi Perkuliahan', '40k–150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(631, 'uiux', 'UI Design Landing Page', 'Start 150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(632, 'uiux', 'UI Design Website Company Profile', 'Start 300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(633, 'uiux', 'UI Design Website Portfolio', 'Start 250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(634, 'uiux', 'UX Research Basic', 'Start 150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(635, 'uiux', 'Riset Target User', 'Start 150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(636, 'uiux', 'Analisis Kompetitor Aplikasi', 'Start 200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(637, 'uiux', 'Analisis Kompetitor Website', 'Start 200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(638, 'uiux', 'User Persona', 'Start 100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(639, 'uiux', 'Customer Journey Map', 'Start 150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(640, 'uiux', 'User Flow', 'Start 100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(641, 'uiux', 'Task Flow', 'Start 100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(642, 'uiux', 'Information Architecture', 'Start 150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(643, 'uiux', 'Sitemap Website / Aplikasi', 'Start 100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(644, 'uiux', 'Problem Statement UX', 'Start 100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(645, 'uiux', 'UX Strategy Sederhana', 'Start 250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(646, 'uiux', 'UI Design Website Personal Branding', 'Start 250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(647, 'uiux', 'UI Design Website UMKM', 'Start 300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(648, 'uiux', 'UI Design Website Sekolah / Kampus', 'Start 400k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(649, 'uiux', 'UI Design Website Event', 'Start 250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(650, 'uiux', 'UI Design Website Blog / News', 'Start 300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(651, 'uiux', 'UI Design Website Marketplace', 'Start 700k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(652, 'uiux', 'UI Design Website E-Commerce', 'Start 700k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(653, 'uiux', 'UI Design Website SaaS', 'Start 800k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(654, 'uiux', 'UI Design Website Membership', 'Start 500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(655, 'uiux', 'UI Design Mobile App Basic', 'Start 300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(656, 'uiux', 'UI Design Android App', 'Start 300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(657, 'uiux', 'UI Design iOS App', 'Start 300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(658, 'uiux', 'UI Design Aplikasi Edukasi', 'Start 500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(659, 'uiux', 'UI Design Aplikasi Booking', 'Start 500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(660, 'uiux', 'UI Design Aplikasi Marketplace', 'Start 700k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(661, 'uiux', 'UI Design Aplikasi Finance', 'Start 700k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(662, 'uiux', 'UI Design Aplikasi Kesehatan', 'Start 600k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(663, 'uiux', 'UI Design Aplikasi Food Delivery', 'Start 700k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(664, 'uiux', 'UI Design Aplikasi Chat / Komunitas', 'Start 600k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(665, 'uiux', 'UI Design Aplikasi Absensi', 'Start 400k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(666, 'uiux', 'UI Design Aplikasi Kasir / POS', 'Start 700k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(667, 'uiux', 'Desain Login Page', 'Start 100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(668, 'uiux', 'Desain Register Page', 'Start 100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(669, 'uiux', 'Desain Forgot Password Page', 'Start 75k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(670, 'uiux', 'Desain Home Page', 'Start 150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(671, 'uiux', 'Desain Profile Page', 'Start 100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(672, 'uiux', 'Desain Setting Page', 'Start 100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(673, 'uiux', 'Desain Search Page', 'Start 100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(674, 'uiux', 'Desain Product Detail Page', 'Start 150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(675, 'uiux', 'Desain Cart Page', 'Start 150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(676, 'uiux', 'Desain Checkout Page', 'Start 150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(677, 'uiux', 'Desain Payment Page', 'Start 150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(678, 'uiux', 'Desain Order Tracking Page', 'Start 150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(679, 'uiux', 'Desain Notification Page', 'Start 100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(680, 'uiux', 'Desain Dashboard Page', 'Start 200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(681, 'uiux', 'Desain Report Page', 'Start 200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(682, 'uiux', 'Desain Form Page', 'Start 100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(683, 'uiux', 'Redesign Landing Page', 'Start 200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(684, 'uiux', 'Redesign Website Lama', 'Start 400k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(685, 'uiux', 'Redesign Mobile App', 'Start 500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(686, 'uiux', 'Redesign Dashboard', 'Start 500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(687, 'uiux', 'Redesign Halaman Login', 'Start 100k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(688, 'uiux', 'Redesign Halaman Checkout', 'Start 200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(689, 'uiux', 'Redesign Halaman Produk', 'Start 200k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(690, 'uiux', 'Redesign UI agar Lebih Modern', 'Start 250k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(691, 'uiux', 'Redesign UI agar Mobile Friendly', 'Start 300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(692, 'uiux', 'Redesign UI Figma dari Screenshot', 'Start 150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(693, 'uiux', 'Redesign UI dari Referensi', 'Start 150k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(694, 'uiux', 'Redesign UI dari Website Kompetitor', 'Start 300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(695, 'uiux', 'Paket Landing Page Basic', 'Start 300k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(696, 'uiux', 'Paket Website Company Profile', 'Start 500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(697, 'uiux', 'Paket Mobile App 5 Page', 'Start 500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(698, 'uiux', 'Paket Mobile App 10 Page', 'Start 900k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(699, 'uiux', 'Paket Dashboard Admin Basic', 'Start 700k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(700, 'uiux', 'Paket E-Commerce Basic', 'Start 1.000k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(701, 'uiux', 'Paket Prototype Figma', 'Start 500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(702, 'uiux', 'Paket Redesign Website', 'Start 500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(703, 'uiux', 'Paket UX Audit + Report', 'Start 500k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL),
(704, 'uiux', 'Paket Design System Basic', 'Start 750k', 'Pengerjaan cepat & garansi kualitas hasil terbaik.', NULL)
ON CONFLICT (id) DO UPDATE SET category=EXCLUDED.category, name=EXCLUDED.name, price=EXCLUDED.price, description=EXCLUDED.description, badge=EXCLUDED.badge;
